### ISSUE TITLE
Error building on Windows

### ISSUE THREAD

**Issue by jflam** [atom-archive/electron-starter#47]
Now I am running this on an unreleased version of Windows. I'll try on my Windows 8.1 machine when I get home to see if there's any difference.

```
~\Source\Repos\cccc\atom-shell-starter
» .\script\build
Node: v0.10.33
npm: v1.4.28
Python: v2.7.9
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by paulcbetts** [comment]
Is Git installed on your machine? The easiest way to get this going on Windows is:

1. Install 32-bit Node.js 0.10.x
1. Install Python 2.7
1. Install GitHub for Windows, open its "Git Shell"

In that PowerShell prompt, do your script/building

**Comment by jflam** [comment]
My git is:

» git --version
git version 1.9.5.msysgit.0

**Comment by jflam** [comment]
This is from a locally cloned forked copy of your repo.

**Comment by jflam** [comment]
Just repro'd on my Windows 8.1 machine at home. Fresh install of node 0.10.33 and Python 2.7.9:

~\Source\Repos\cc\atom-shell-starter
» .\script\build
Node: v0.10.33
npm: v1.4.28
Python: v2.7.9
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by jflam** [comment]
Now I'm getting the same error on my Mac - 10.10.3. This is the stack trace (slightly different version of Node - 0.10.36 and Python 2.7.6), but same error.

>> script/build
Node: v0.10.36
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by jflam** [comment]
This feels like some dependency is missing, especially since I'm a node newb. Sadly that stack trace doesn't look very helpful. Suggestions on how to debug would be great.

**Comment by paulcbetts** [comment]
@jflam Try `script/grunt --verbose --stack`

**Comment by jflam** [comment]
There are things happening with paths that I don't understand. For example:

» .\script\grunt.cmd --verbose --stack
Grunt command does not exist at: "C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\.bin\grunt.cmd"
Run script/bootstrap to install Grunt
~\Source\Repos\cccc\atom-shell-starter

But that file is actually there:

» ls C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\.bin\grunt.cmd


    Directory: C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\.bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/18/2015  10:06 PM            186 grunt.cmd

If I run that file directly with the parameters that we want from the script

var args = ['--gruntfile', path.resolve('build', 'Gruntfile.coffee')];

~\Source\Repos\cccc\atom-shell-starter\build
» .\node_modules\.bin\grunt.cmd --verbose --stack gruntfile.coffee
Initializing
Command-line options: --verbose, --stack

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bower-task" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-bower-task\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-bower-task\package.json...OK
Loading "bower_task.js" tasks...OK
+ bower

Registering "grunt-coffeelint" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-coffeelint\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-coffeelint\package.json...OK
Loading "coffeelint.js" tasks...OK
+ coffeelint

Registering "grunt-lesslint" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-lesslint\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-lesslint\package.json...OK
Loading "less-lint-task.js" tasks...OK
+ lesslint
Loading "lint-utils.js" tasks...OK
>> No tasks were registered or unregistered.

Registering "grunt-cson" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-cson\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-cson\package.json...OK
Loading "cson-task.js" tasks...OK
+ cson

Registering "grunt-contrib-csslint" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-csslint\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-csslint\package.json...OK
Loading "csslint.js" tasks...OK
+ csslint

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-coffee\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-coffee\package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-contrib-less" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-less\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-contrib-less\package.json...OK
Loading "less.js" tasks...OK
+ less

Registering "grunt-shell" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-shell\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-shell\package.json...OK
Loading "shell.js" tasks...OK
+ shell

Registering "grunt-build-atom-shell" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-build-atom-shell\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-build-atom-shell\package.json...OK
Loading "build-atom-shell-task.coffee" tasks...OK
+ build-atom-shell, rebuild-atom-shell, rebuild-native-modules
Loading "task-helpers.coffee" tasks...OK
>> No tasks were registered or unregistered.

Registering "grunt-atom-shell-installer" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-atom-shell-installer\package.json...
OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-atom-shell-installer\package.json...
OK
Loading "index.js" tasks...OK
+ create-windows-installer

Registering "grunt-peg" local Npm module tasks.
Reading C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-peg\package.json...OK
Parsing C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-peg\package.json...OK
Loading "peg.js" tasks...OK
+ peg

Registering "tasks" tasks.
Loading "build-task.coffee" tasks...OK
+ build
Loading "check-licenses-task.coffee" tasks...OK
+ check-licenses
Loading "clean-task.coffee" tasks...OK
+ clean, partial-clean
Loading "codesign-task.coffee" tasks...OK
+ codesign
Loading "copy-info-plist-task.coffee" tasks...OK
+ copy-info-plist
Loading "dump-symbols-task.coffee" tasks...OK
+ dump-symbols
Loading "generate-license-task.coffee" tasks...OK
+ generate-license
Loading "license-overrides.coffee" tasks...OK
>> No tasks were registered or unregistered.
Loading "mkdeb-task.coffee" tasks...OK
+ mkdeb
Loading "mkrpm-task.coffee" tasks...OK
+ mkrpm
Loading "output-disk-space.coffee" tasks...OK
+ output-disk-space
Loading "output-long-paths-task.coffee" tasks...OK
+ output-long-paths
Loading "set-exe-icon-task.coffee" tasks...OK
+ set-exe-icon
Loading "set-version-task.coffee" tasks...OK
+ set-version
Loading "spec-task.coffee" tasks...OK
+ run-specs
Loading "task-helpers.coffee" tasks...OK
>> No tasks were registered or unregistered.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK
Loading "Gruntfile.coffee" tasks...OK
+ ci, compile, default, lint, test

Running tasks: gruntfile.coffee
Warning: Task "gruntfile.coffee" not found. Use --force to continue.
Error: Task "gruntfile.coffee" not found.
  at Task.run (C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt\lib\util\task.js:179:28)
  at C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt\lib\grunt.js:161:39
  at Array.forEach (native)
  at Object.grunt.tasks (C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt\lib\grunt.js:161:9)

  at Object.module.exports [as cli] (C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt\lib\gru
nt\cli.js:38:9)
  at Object.<anonymous> (C:\Users\John\Source\Repos\cccc\atom-shell-starter\build\node_modules\grunt-cli\bin\grunt:45:20
)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by jugglingnutcase** [comment]
i seem to be experiencing this same issue, but i have the bits from #49 in my folder already (i'm on commit a031fe3). Here's what i see for `script/build`:

```
C:\Users\james_000\Documents\src\atom-shell-starter [master]> .\script\build
    Node: v0.10.36
    npm: v1.4.28
    Python: v2.7.9
    Installing build modules...
    Installing apm...
    Removing scrollbar-style done
    Installing modules done
    Deduping modules done
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: spawn ENOENT
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

How can i get more verbose output? i tried `--no-quiet` and `script/grunt --verbose --stack` but it doesn't get past the first error.

---

i also get the same problems with `script/grunt` shown in previous comments, but i'm not sure if it's connected to the error i'm seeing above. Here's my grunt problems:

    C:\Users\james_000\Documents\src\atom-shell-starter [master]> .\script\grunt
    Grunt command does not exist at: "C:\Users\james_000\Documents\src\atom-shell-starter\build\node_modules\.bin\grunt.cmd"
    Run script/bootstrap to install Grunt

Which makes it look like i did something wrong, but... but... this:

    C:\Users\james_000\Documents\src\atom-shell-starter [master]> ls C:\Users\james_000\Documents\src\atom-shell-starter\build\node_modules\.bin\grunt.cmd
    
    
        Directory: C:\Users\james_000\Documents\src\atom-shell-starter\build\node_modules\.bin
    
    
    Mode                LastWriteTime     Length Name
    ----                -------------     ------ ----
    -a---         1/28/2015  11:25 AM        186 grunt.cmd

Maybe some paths are messed up? but running grunt in the `build` directory works fine... i plan to keep digging on this, but i'm not getting very far at the moment.

**Comment by paulcbetts** [comment]
@jugglingnutcase Try it now, I reverted everything to the way it was before

**Comment by jugglingnutcase** [comment]
Wow, that was quick! Looks like it's working... unfortunately the build part isn't as quick as you are (on this machine at least). i'll speak up if this is still busted once the build process is done.

Thanks :grinning:

**Comment by paulcbetts** [comment]
@jugglingnutcase The first build takes forevvvvvvver, but future runs are fairly fast

**Comment by jugglingnutcase** [comment]
i guess so! especially on this little laptop! lesson learned, next time i start it right before a nap.

**Comment by jugglingnutcase** [comment]
Does reverting that bork the spaces in paths stuff? i wouldn't think that spaces in paths could cause an issue (but i'm the opposite of a node expert).

**Comment by paulcbetts** [comment]
It does, but I'd rather it work for some people than zero people :)

**Comment by lllama** [comment]
Sorry about this - I was over zealous with the quoting. I'm fairly confident that it's just the args being passed to the grunt command that need them removing, as args to the process start call are handled properly.

**Comment by jugglingnutcase** [comment]
Oddly enough, [my first ever pull request](https://github.com/Code52/DownmarkerWPF/pull/119) was meant to fix builds over paths with spaces.

**Comment by paulcbetts** [comment]
@lllama No worries, I just wanted to unblock people until we can figure out what's going on

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
