### ISSUE TITLE
Windows Build fails during "build-atom-shell" task

### ISSUE THREAD

**Issue by lllama** [atom-archive/electron-starter#54]
Different platform than #27, so opening a new issue here. Here's the command output:

```
C:\atom-shell-starter>script\build.cmd
Node: v0.10.36
npm: v1.4.28
Python: v2.7.6
Installing build modules...
Installing apm...
Installing modules done
Deduping modules done
Running "build-atom-shell" task
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 127, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 26, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 54, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "C:\Users\FELIXI~1\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 150, in execute_stdout
>>     execute(argv)
>>   File "C:\Users\FELIXI~1\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 138, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 127, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 26, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 54, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "C:\Users\FELIXI~1\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 150, in execute_stdout
>>     execute(argv)
>>   File "C:\Users\FELIXI~1\AppData\Local\Temp\eightoheight-build\atom-shell\script\lib\util.py", line 138, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
Aborted due to warnings.

C:\atom-shell-starter>
```

Looks like it's failing to build atom-shell but I can successfully build this separately from a checkout of its repo. Does the starter project use a specific revision, or does it track master?

**Comment by lllama** [comment]
Looks like this is due to path lengths. Atom-shell will bootstrap properly when checked out into the root directory. The "build-atom-shell" task checks out atom-shell into the temp directory defined by the TMP environment variable. Changing this to "c:\t" or something very short will help. You also need to change the package name to something very short (single char) as well.

Gruntfile could be modified to change the build directory name to something shorter as well.

**Comment by mmurdoch** [comment]
This looks to be the same issue as #60.

**Comment by paulcbetts** [comment]
Update your version of Atom Shell that you're using (via `build/Gruntfile.coffee`) to a more recent version to fix this

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
