### ISSUE TITLE
App Name and Icon in Notification Center Won't Change from Atom

### ISSUE THREAD

**Issue by drewbkoch** [atom-archive/electron-starter#74]
Even though I've set my app's icon in the resources folder and changed the name of my app in the package.json, it still thinks my app's name is "Atom" and the icon it should use is the Atom icon in Banner notifications and the Notification Center. 

Is there a way to change this?

Here's my repo fyi: https://github.com/drewbkoch/gmail

Thanks :)

![screen shot 2015-04-28 at 7 20 38 pm](https://cloud.githubusercontent.com/assets/3522459/7399843/859d0630-ee6d-11e4-85c0-41dee521ea91.png)

**Comment by paulcbetts** [comment]
What's interesting is that the sample is never called Atom anywhere (it should be EightOhEight), I'm not sure where it's getting that name. OS X will hold onto some of this metadata for awhile, so it might be showing you a stale version - moving the .app to another folder sometimes fixes it. What does your info.plist in the final result look like?

**Comment by drewbkoch** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>Gmail</string>
	<key>CFBundleIconFile</key>
	<string>app.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.github.atom</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Gmail</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.0.1-528f737</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>0.0.1-528f737</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.lifestyle</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.8</string>
	<key>NSAppleScriptEnabled</key>
	<string>YES</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>AtomApplication</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
</dict>
</plist>

**Comment by drewbkoch** [comment]
What's weird too is that the app icon and name in the dock and everywhere else is correct...

**Comment by drewbkoch** [comment]
Moving the .app to a different folder didn't do it either :/

**Comment by paulcbetts** [comment]
Looks right except for `CFBundleIdentifier`. Hm.

**Comment by drewbkoch** [comment]
You're correct, I do. Is there any way to get around this conflict?

**Comment by drewbkoch** [comment]
Interesting, it seems if I change these to the following, it works:
```    
 <key>CFBundleExecutable</key>
 <string>Atom</string>

 <key>CFBundleIdentifier</key>
 <string>com.drewbkoch.gmail</string>

**Comment by paulcbetts** [comment]
Yep, we just need to change up that template to set the bundle identifier too. Changing it by-hand will work fine as well

**Comment by drewbkoch** [comment]
Cool thanks
ᐧ

On Wed, Apr 29, 2015 at 4:12 PM, Paul Betts <notifications@github.com>
wrote:

> Yep, we just need to change up that template to set the bundle identifier
> too. Changing it by-hand will work fine as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/electron-starter/issues/74#issuecomment-97611625>
> .
>



-- 
--
Drew Koch
drewkoch.com

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
