### ISSUE TITLE
bootstrap script fails: specified procedure could not be found

### ISSUE THREAD

**Issue by zaggino** [atom-archive/electron-starter#78]
```
$ node script/bootstrap
Node: v0.12.2
npm: v2.7.4
Python: v2.7.9
Installing build modules...
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

d:\dev\electron-starter\apm\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: The specified procedure could not be found.

d:\dev\electron-starter\apm\node_modules\atom-package-manager\node_modules\keytar\build\Release\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\dev\electron-starter\apm\node_modules\atom-package-manager\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (d:\dev\electron-starter\apm\node_modules\atom-package-manager\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by plrthink** [comment]
I have the some issue when build on fresh installed windows 8.1. Is there updates about this?

**Comment by plrthink** [comment]
My environment is: node: v0.12.2, npm: v2.7.4, python: v2.7.9 and vs2013 community on windows8.1 pro build 9600.

**Comment by paulcbetts** [comment]
You have to use node 0.10.x because of apm weirdness

**Comment by plrthink** [comment]
@paulcbetts Thanks for your help. I switched to node v0.10.36 and bootstrap process passed successfully. 

But there's a new problem occurs. When I run `npm run build`, it was hanging on `Running "build-atom-shell" task` for several hours without logging what happening. Any idea?

**Comment by plrthink** [comment]
Oh, I think `build-atom-shell` task is downloading a tons of file so it seems like sleeping.

Anyway, thanks.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/electron-starter), this package is no longer maintained and is deprecated. We recommend that people use [electron-prebuilt](https://github.com/mafintosh/electron-prebuilt) and [electron-packager](https://github.com/maxogden/electron-packager) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
